CREATE COLUMN TABLE "DIPROJECTS"."TEXT_WORDS"(
	"TEXT_ID" BIGINT,
	"LANGUAGE" NVARCHAR(2),
	"TYPE" NVARCHAR(15),
	"WORD" NVARCHAR(80),
	"COUNT" INTEGER,
	PRIMARY KEY (
		"TEXT_ID",
		"TYPE",
		"WORD"
	)
)
